global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'workspace-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['workspace-service:8081']
        labels:
          service: 'workspace-service'

  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['booking-service:8082']
        labels:
          service: 'booking-service'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8083']
        labels:
          service: 'payment-service'

